#pragma once

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <string>

#include "../../DataStructures/RAPTOR/Data.h"
#include "DynamicTransferCommandBase.h"

using namespace Shell;

class RAPTORToDynamic : public ParameterizedCommand {
public:
    RAPTORToDynamic(BasicShell& shell)
        : ParameterizedCommand(shell, "raptorToDynamic", "Converts a RAPTOR object into a DynamicTimeTable object.") {
        addParameter("Input binary (RAPTOR Data)");
        addParameter("Output binary (DynamicTimeTable data)");
    }

    virtual void execute() noexcept override {
        const std::string inputFile = getParameter("Input binary (RAPTOR Data)");
        const std::string outputFile = getParameter("Output binary (DynamicTimeTable data)");

        RAPTOR::Data data(inputFile);
        data.printInfo();

        DynamicTimeTable::Data dynamicTimeTable(data);
        dynamicTimeTable.printInfo();
        dynamicTimeTable.serialize(outputFile);
    }
};

class LoadAndApplyDynamicPartition : public ParameterizedCommand {
public:
    LoadAndApplyDynamicPartition(BasicShell& shell)
        : ParameterizedCommand(
              shell, "loadAndApplyDynamicPartition",
              "Loads a partition file generated by a black-box partitioner and applies the cell ids to the stops.") {
        addParameter("Input partition file");
        addParameter("Input binary (DynamicTimeTable Data)");
    }

    virtual void execute() noexcept override {
        const std::string partitionFile = getParameter("Input partition file");
        const std::string dynamicFile = getParameter("Input binary (DynamicTimeTable Data)");

        DynamicTimeTable::Data dynamicTimeTable(dynamicFile);
        dynamicTimeTable.printInfo();

        dynamicTimeTable.createCompactLayoutGraph();
        dynamicTimeTable.readPartitionFile(partitionFile);

        dynamicTimeTable.serialize(dynamicFile);
    }
};

class BuildDynamicQueryData : public ParameterizedCommand {
public:
    BuildDynamicQueryData(BasicShell& shell)
        : ParameterizedCommand(
              shell, "buildDynamicQueryData",
              "Loads a DynamicTimeTable and builds the QueryData structure to test export compilation.") {
        addParameter("Input binary (DynamicTimeTable Data)");
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        DynamicTimeTable::Data dynamicTimeTable = loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"));
        const auto queryData = QueryDataBuilder()(dynamicTimeTable, "DynamicQueryData", true);
        validateDynamicQueryData(queryData, dynamicTimeTable, "");
    }
};

class BuildInitialTransferStore : public ParameterizedCommand {
public:
    BuildInitialTransferStore(BasicShell& shell)
        : ParameterizedCommand(shell, "buildInitialTransferStore",
                               "Loads a DynamicTimeTable and builds the initial transfer store (full set).") {
        addParameter("Input binary (DynamicTimeTable Data)");
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        DynamicTimeTable::Data dynamicTimeTable = loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"));
        const auto queryData = QueryDataBuilder()(dynamicTimeTable);

        TransferStoreType store;
        TransferUpdater updater(store);
        InitialTransferStoreBuilder(TransferSetSelection::Full, 1, true)(updater, queryData);
    }
};

class SimulateDynamicUpdate : public DynamicTransferCommandBase {
public:
    SimulateDynamicUpdate(BasicShell& shell)
        : DynamicTransferCommandBase(
              shell, "simulateDynamicUpdates",
              "Simulates and applies dynamic updates, measuring execution time and printing a summary.") {
        addParameter("Input binary (DynamicTimeTable Data)");
        addParameter("Current time (seconds)");
        addSimulationParameters("42");
        addParameter("Number of threads", "max");
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        const int nowSeconds = getParameter<int>("Current time (seconds)");
        const int threads = numberOfThreads();

        DynamicTimeTable::Data dynamicTimeTable = loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"));
        const auto queryData = QueryDataBuilder()(dynamicTimeTable);
        validateDynamicQueryData(queryData, dynamicTimeTable, "Initial");

        TransferStoreType store;
        TransferUpdater transferUpdater(store);
        InitialTransferStoreBuilder(TransferSetSelection::Full, threads)(transferUpdater, queryData);

        DynamicTimeTable::Algo::UpdateSimulationStats simStats{};
        const DynamicTimeTable::PendingUpdates updates =
            UpdateGenerator(simulationConfig())(dynamicTimeTable, nowSeconds, &simStats);

        std::cout << "Applying updates..." << std::endl;
        const TimedAppliedUpdate applied = applyIncrementalUpdateTimed(dynamicTimeTable, transferUpdater, updates, threads);
        validateDynamicQueryData(applied.applied.queryData, dynamicTimeTable, "Updated");

        std::cout << "Update pipeline finished in " << applied.duration << std::endl;
        if (applied.applied.changes != nullptr) {
            printSimulationSummary(simStats, updates, applied.applied.statistics, *applied.applied.changes);
        }
    }
};

class SimulateAndCompareTransferUpdate : public DynamicTransferCommandBase {
public:
    SimulateAndCompareTransferUpdate(BasicShell& shell)
        : DynamicTransferCommandBase(
              shell, "simulateAndCompareTransferUpdate",
              "Builds a dynamic transfer store, simulates one update, and compares incremental full/reduced exports "
              "against a fresh rebuild.") {
        addParameter("Input binary (DynamicTimeTable Data)");
        addParameter("Current time (seconds)");
        addSimulationParameters("42");
        addTransferSetParameters();
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        const TransferSetConfig transfers = transferSetConfig();

        DynamicTimeTable::Data dynamicTimeTable = loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"));
        const auto queryData = QueryDataBuilder()(dynamicTimeTable, "initial DynamicQueryData");
        validateDynamicQueryData(queryData, dynamicTimeTable, "Initial");

        TransferStoreType store;
        TransferUpdater transferUpdater(store);
        InitialTransferStoreBuilder(transfers.selection, transfers.threads)(transferUpdater, queryData);
        InitialExportValidator(transfers.kinds, transfers.threads)(transferUpdater, queryData);

        const UpdateComparisonResult result = simulateApplyAndCompare(dynamicTimeTable,
                                                                      transferUpdater,
                                                                      simulationConfig(),
                                                                      getParameter<int>("Current time (seconds)"),
                                                                      transfers.threads,
                                                                      transfers.kinds);
        validateDynamicQueryData(result.applied.queryData, dynamicTimeTable, "Updated");

        if (result.applied.changes != nullptr) {
            printSimulationSummary(result.simulationStats, result.pendingUpdates, result.applied.statistics, *result.applied.changes);
            printChangeDetails(*result.applied.changes);
        }

        std::cout << (result.ok ? "\nTransfer update comparison PASSED for requested transfer set(s)."
                                : "\nTransfer update comparison FAILED.")
                  << std::endl;
    }
};

class SimulateAndCompareTransferUpdates : public DynamicTransferCommandBase {
public:
    SimulateAndCompareTransferUpdates(BasicShell& shell)
        : DynamicTransferCommandBase(
              shell, "simulateAndCompareTransferUpdates",
              "Builds a baseline transfer store, then runs independent seeded update comparisons for full/reduced exports.") {
        addParameter("Input binary (DynamicTimeTable Data)");
        addParameter("Current time (seconds)", "28800");
        addParameter("Base Random seed", "1");
        addParameter("Iterations", "200");
        addParameter("Output File Path", "simulation_output.txt");
        addParameter("Temp Store Path", "base_store.tmp");
        addSimulationRateParameters("100", "100", "100");
        addTransferSetParameters();
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        const int nowSeconds = getParameter<int>("Current time (seconds)");
        const uint32_t baseSeed = static_cast<uint32_t>(getParameter<int>("Base Random seed"));
        const int iterations = getParameter<int>("Iterations");
        const std::string tempStorePath = getParameter("Temp Store Path");
        const TransferSetConfig transfers = transferSetConfig();

        DynamicTimeTable::Data baseDynamicTimeTable =
            loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"), "Base DynamicTimeTable", false);
        const auto baseQueryData = QueryDataBuilder()(baseDynamicTimeTable, "initial Base DynamicQueryData");
        validateDynamicQueryData(baseQueryData, baseDynamicTimeTable, "Initial");

        TransferStoreType baseStore;
        TransferUpdater baseTransferUpdater(baseStore);
        InitialTransferStoreBuilder(transfers.selection, transfers.threads)(baseTransferUpdater, baseQueryData);
        InitialExportValidator(transfers.kinds, transfers.threads)(baseTransferUpdater, baseQueryData);

        std::cout << "Serializing baseline store to disk..." << std::endl;
        baseStore.serialize(tempStorePath);

        std::ofstream outFile(getParameter("Output File Path"));
        if (!outFile) {
            std::cerr << "Failed to open output file: " << getParameter("Output File Path") << std::endl;
            return;
        }

        std::cout << "Starting simulation loop across " << iterations << " iterations..." << std::endl;
        bool divergenceFound = false;
        for (int i = 0; i < iterations; ++i) {
            const uint32_t currentSeed = baseSeed + static_cast<uint32_t>(i);
            std::cout << "\rRunning iteration " << (i + 1) << "/" << iterations
                      << " (Seed: " << currentSeed << ")..." << std::flush;

            DynamicTimeTable::Data dynamicTimeTableCopy = baseDynamicTimeTable;
            TransferStoreType storeCopy(tempStorePath);
            TransferUpdater transferUpdater(storeCopy);

            outFile << "=== Iteration: " << (i + 1) << " | Seed: " << currentSeed << " ===\n";
            const UpdateComparisonResult result = simulateApplyAndCompare(dynamicTimeTableCopy,
                                                                          transferUpdater,
                                                                          simulationConfigWithSeed(currentSeed),
                                                                          nowSeconds,
                                                                          transfers.threads,
                                                                          transfers.kinds,
                                                                          &outFile);
            outFile << "Status: " << (result.ok ? "Success" : "FAILED") << "\n\n";

            if (!result.ok) {
                divergenceFound = true;
                std::cout << "\n\n!!! DIVERGENCE DETECTED !!!" << std::endl;
                std::cout << "Replication Seed: " << currentSeed << std::endl;
                std::cout << "Check file details at: " << getParameter("Output File Path") << std::endl;
                if (result.applied.changes != nullptr) {
                    outFile << "\n[!] CRITICAL DIVERGENCE FOUND FOR SEED: " << currentSeed << "\n";
                    printChangeDetails(*result.applied.changes, outFile);
                }
            }
        }

        std::remove(tempStorePath.c_str());
        if (!divergenceFound) {
            std::cout << "\nAll iterations completed successfully. No transfer divergences found." << std::endl;
        }
    }
};

class SimulateAndDetailCompareTransferTimeline : public DynamicTransferCommandBase {
public:
    SimulateAndDetailCompareTransferTimeline(BasicShell& shell)
        : DynamicTransferCommandBase(
              shell, "simulateAndDetailCompareTransferTimeline",
              "Runs sequential minute-by-minute updates from start to end time and compares full/reduced incremental exports against rebuilds.") {
        addParameter("Input binary (DynamicTimeTable Data)");
        addParameter("Start time (seconds)", "0");
        addParameter("End time (seconds)", "86400");
        addParameter("Step seconds", "60");
        addParameter("Base Random seed", "1");
        addParameter("Output File Path", "timeline_simulation_output.txt");
        addSimulationRateParameters("0", "0", "0");
        addTransferSetParameters();
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        const int startTimeSeconds = getParameter<int>("Start time (seconds)");
        const int endTimeSeconds = getParameter<int>("End time (seconds)");
        const int stepSeconds = std::max(1, getParameter<int>("Step seconds"));
        const uint32_t baseSeed = static_cast<uint32_t>(getParameter<int>("Base Random seed"));
        const TransferSetConfig transfers = transferSetConfig();

        std::ofstream outFile(getParameter("Output File Path"));
        if (!outFile) {
            std::cerr << "Failed to open output file: " << getParameter("Output File Path") << std::endl;
            return;
        }

        DynamicTimeTable::Data dynamicTimeTable = loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"));
        const auto queryData = QueryDataBuilder()(dynamicTimeTable, "initial DynamicQueryData");
        validateDynamicQueryData(queryData, dynamicTimeTable, "Initial");

        TransferStoreType store;
        TransferUpdater transferUpdater(store);
        InitialTransferStoreBuilder(transfers.selection, transfers.threads)(transferUpdater, queryData);

        bool divergenceFound = false;
        int stepIndex = 0;
        for (int now = startTimeSeconds; now < endTimeSeconds; now += stepSeconds, ++stepIndex) {
            const uint32_t seed = baseSeed + static_cast<uint32_t>(stepIndex);
            std::cout << "\rTimeline step " << (stepIndex + 1) << " at t=" << now
                      << "s (Seed: " << seed << ")..." << std::flush;

            outFile << "=== Timeline step: " << (stepIndex + 1)
                    << " | Current time: " << now
                    << " | Seed: " << seed << " ===\n";

            const UpdateComparisonResult result = simulateApplyAndCompare(dynamicTimeTable,
                                                                          transferUpdater,
                                                                          simulationConfigWithSeed(seed),
                                                                          now,
                                                                          transfers.threads,
                                                                          transfers.kinds,
                                                                          &outFile);
            outFile << "Status: " << (result.ok ? "Success" : "FAILED") << "\n\n";

            if (!result.ok) {
                divergenceFound = true;
                std::cout << "\n\n!!! TIMELINE DIVERGENCE DETECTED !!!" << std::endl;
                std::cout << "Current time (seconds): " << now << std::endl;
                std::cout << "Replication Seed: " << seed << std::endl;
                std::cout << "Check file details at: " << getParameter("Output File Path") << std::endl;
                if (result.applied.changes != nullptr) {
                    outFile << "\n[!] CRITICAL TIMELINE DIVERGENCE AT t=" << now << " SEED=" << seed << "\n";
                    printChangeDetails(*result.applied.changes, outFile);
                }
                break;
            }
        }

        if (!divergenceFound) {
            std::cout << "\nTimeline comparison completed successfully from " << startTimeSeconds
                      << " to " << endTimeSeconds << " seconds in " << stepSeconds
                      << " second steps." << std::endl;
        }
    }
};


class SimulateTransferTimeline : public DynamicTransferCommandBase {
public:
    SimulateTransferTimeline(BasicShell& shell)
        : DynamicTransferCommandBase(
              shell, "simulateTransferTimeline",
              "Runs sequential minute-by-minute updates from start to end time.") {
        addParameter("Input binary (DynamicTimeTable Data)");
        addParameter("Start time (seconds)", "0");
        addParameter("End time (seconds)", "86400");
        addParameter("Step seconds", "60");
        addParameter("Base Random seed", "1");
        addParameter("Output File Path", "timeline_simulation_output.txt");
        addSimulationRateParameters("0", "0", "0");
        addTransferSetParameters();
    }

    virtual void execute() noexcept override {
        using namespace DynamicTransferScenarios;

        const int startTimeSeconds = getParameter<int>("Start time (seconds)");
        const int endTimeSeconds = getParameter<int>("End time (seconds)");
        const int stepSeconds = std::max(1, getParameter<int>("Step seconds"));
        const uint32_t baseSeed = static_cast<uint32_t>(getParameter<int>("Base Random seed"));
        const TransferSetConfig transfers = transferSetConfig();

        std::ofstream outFile(getParameter("Output File Path"));
        if (!outFile) {
            std::cerr << "Failed to open output file: " << getParameter("Output File Path") << std::endl;
            return;
        }

        DynamicTimeTable::Data dynamicTimeTable =
            loadDynamicTimeTable(getParameter("Input binary (DynamicTimeTable Data)"));

        const auto initialQueryData =
            QueryDataBuilder()(dynamicTimeTable, "initial DynamicQueryData");
        validateDynamicQueryData(initialQueryData, dynamicTimeTable, "Initial");

        TransferStoreType store;
        TransferUpdater transferUpdater(store);
        InitialTransferStoreBuilder(transfers.selection, transfers.threads)(
            transferUpdater, initialQueryData);

        int stepIndex = 0;
        for (int now = startTimeSeconds; now < endTimeSeconds; now += stepSeconds, ++stepIndex) {
            const uint32_t seed = baseSeed + static_cast<uint32_t>(stepIndex);

            std::cout << "\rTimeline step " << (stepIndex + 1)
                      << " at t=" << now
                      << "s (Seed: " << seed << ")..."
                      << std::flush;

            outFile << "=== Timeline step: " << (stepIndex + 1)
                    << " | Current time: " << now
                    << " | Seed: " << seed << " ===\n";

            DynamicTimeTable::Algo::UpdateSimulationStats simStats{};
            const DynamicTimeTable::PendingUpdates updates =
                UpdateGenerator(simulationConfig())(dynamicTimeTable, now, &simStats);

            const TimedAppliedUpdate applied =
                applyIncrementalUpdateTimed(
                    dynamicTimeTable,
                    transferUpdater,
                    updates,
                    transfers.threads);

            outFile << "Applied update in "
                    << applied.duration.count()
                    << " µs\n";
        }

        std::cout << "\nTimeline completed successfully from "
                  << startTimeSeconds
                  << " to "
                  << endTimeSeconds
                  << " seconds in "
                  << stepSeconds
                  << " second steps."
                  << std::endl;
    }
};
